import type { FontScript } from '@core/fonts/domain/FontScript';

/** One family per writing system: what a stack is, spelled out. */
export type FontStackFaces = Readonly<Record<FontScript, string>>;

export interface CatalogFontStack {
  /** Stable name a template refers to. Outlives any of the faces it names. */
  readonly id: string;
  readonly faces: FontStackFaces;
}

// Every stack the catalog ships: an id a template names, and the face that
// draws each writing system under it. Written out per stack rather than
// derived from a table of shared fallbacks — repetitive on purpose, because
// the whole point of a stack is that you can read what it will paint without
// following a lookup somewhere else. Change one face and only that stack
// changes.
//
// A stack keeps its own Latin face for every script that face also draws, so
// a family shipping Cyrillic is never displaced by another. Sixteen families
// here ship Cyrillic and seven ship Greek; displacing them would swap type
// that fits the template for type that merely covers the letters.
//
// The faces filling the rest were chosen to carry the same tone across
// writing systems: a heavy display face falls to a heavy display face, a
// bookish serif to a bookish serif. Script and handwritten faces fall to the
// neutral sans rather than to Amiri — Amiri is a classical book face and
// reads solemn, and being wrong about formality is worse than being wrong
// about texture. Greek is the thinnest bench here, seven families and not one
// display face, so heavy stacks fall to a neutral sans whose weight axis can
// still answer a template asking for 900. Devanagari names Poppins almost
// everywhere; it was designed for both Latin and Devanagari. Kalam is the
// other Devanagari option in the picker.
//
// Every stack is rooted on a Latin face, because that is the shape the gallery
// has: templates start from a Latin display or text family. Nothing in the
// type says so — a template built around a Naskh or Nastaliq face would earn a
// stack of its own, authored the same way.
export const FONT_STACKS: readonly CatalogFontStack[] = [
  {
    id: 'inter',
    faces: {
      latin: 'Inter Variable',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Inter Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'poppins',
    faces: {
      latin: 'Poppins',
      arabic: 'Cairo Variable',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Nunito Variable',
      greek: 'Comfortaa Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'montserrat',
    faces: {
      latin: 'Montserrat Variable',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Montserrat Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'roboto',
    faces: {
      latin: 'Roboto',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Roboto',
      greek: 'Roboto',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'anton',
    faces: {
      latin: 'Anton',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Oswald Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'bebas-neue',
    faces: {
      latin: 'Bebas Neue',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Oswald Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'bangers',
    faces: {
      latin: 'Bangers',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Oswald Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'komika-axis',
    faces: {
      latin: 'Komika Axis',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Oswald Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'manrope',
    faces: {
      latin: 'Manrope Variable',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Manrope Variable',
      greek: 'Manrope Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'nunito',
    faces: {
      latin: 'Nunito Variable',
      arabic: 'Cairo Variable',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Nunito Variable',
      greek: 'Comfortaa Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'raleway',
    faces: {
      latin: 'Raleway Variable',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Raleway Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'dm-sans',
    faces: {
      latin: 'DM Sans Variable',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Inter Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'comfortaa',
    faces: {
      latin: 'Comfortaa Variable',
      arabic: 'Cairo Variable',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Comfortaa Variable',
      greek: 'Comfortaa Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'gabarito',
    faces: {
      latin: 'Gabarito Variable',
      arabic: 'Cairo Variable',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Nunito Variable',
      greek: 'Comfortaa Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'bricolage-grotesque',
    faces: {
      latin: 'Bricolage Grotesque Variable',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Inter Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'oswald',
    faces: {
      latin: 'Oswald Variable',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Oswald Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'bungee',
    faces: {
      latin: 'Bungee',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Oswald Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'righteous',
    faces: {
      latin: 'Righteous',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Oswald Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'playfair-display',
    faces: {
      latin: 'Playfair Display Variable',
      arabic: 'Amiri',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'EB Garamond Variable',
      greek: 'EB Garamond Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Serif Bengali Variable',
      telugu: 'Noto Serif Telugu Variable',
      tamil: 'Noto Serif Tamil Variable',
      thai: 'Noto Serif Thai Variable',
    },
  },
  {
    id: 'eb-garamond',
    faces: {
      latin: 'EB Garamond Variable',
      arabic: 'Amiri',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'EB Garamond Variable',
      greek: 'EB Garamond Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Serif Bengali Variable',
      telugu: 'Noto Serif Telugu Variable',
      tamil: 'Noto Serif Tamil Variable',
      thai: 'Noto Serif Thai Variable',
    },
  },
  {
    id: 'dm-serif-display',
    faces: {
      latin: 'DM Serif Display',
      arabic: 'Amiri',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'EB Garamond Variable',
      greek: 'EB Garamond Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Serif Bengali Variable',
      telugu: 'Noto Serif Telugu Variable',
      tamil: 'Noto Serif Tamil Variable',
      thai: 'Noto Serif Thai Variable',
    },
  },
  {
    id: 'im-fell-english',
    faces: {
      latin: 'IM Fell English',
      arabic: 'Amiri',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'EB Garamond Variable',
      greek: 'EB Garamond Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Serif Bengali Variable',
      telugu: 'Noto Serif Telugu Variable',
      tamil: 'Noto Serif Tamil Variable',
      thai: 'Noto Serif Thai Variable',
    },
  },
  {
    id: 'fraunces',
    faces: {
      latin: 'Fraunces Variable',
      arabic: 'Amiri',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'EB Garamond Variable',
      greek: 'EB Garamond Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Serif Bengali Variable',
      telugu: 'Noto Serif Telugu Variable',
      tamil: 'Noto Serif Tamil Variable',
      thai: 'Noto Serif Thai Variable',
    },
  },
  {
    id: 'lora',
    faces: {
      latin: 'Lora Variable',
      arabic: 'Amiri',
      hebrew: 'Assistant Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Lora Variable',
      greek: 'EB Garamond Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Serif Bengali Variable',
      telugu: 'Noto Serif Telugu Variable',
      tamil: 'Noto Serif Tamil Variable',
      thai: 'Noto Serif Thai Variable',
    },
  },
  {
    id: 'kalam',
    faces: {
      latin: 'Kalam',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Inter Variable',
      greek: 'Inter Variable',
      devanagari: 'Kalam',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'dancing-script',
    faces: {
      latin: 'Dancing Script Variable',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Inter Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'pacifico',
    faces: {
      latin: 'Pacifico',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Inter Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'lobster',
    faces: {
      latin: 'Lobster',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Lobster',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'caveat',
    faces: {
      latin: 'Caveat Variable',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Caveat Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'permanent-marker',
    faces: {
      latin: 'Permanent Marker',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Oswald Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'jetbrains-mono',
    faces: {
      latin: 'JetBrains Mono Variable',
      arabic: 'Vazirmatn Variable',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'JetBrains Mono Variable',
      greek: 'JetBrains Mono Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'vt323',
    faces: {
      latin: 'VT323',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Oswald Variable',
      greek: 'Inter Variable',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },
  {
    id: 'press-start-2p',
    faces: {
      latin: 'Press Start 2P',
      arabic: 'Lalezar',
      hebrew: 'Heebo Variable',
      urdu: 'Noto Nastaliq Urdu',
      cyrillic: 'Press Start 2P',
      greek: 'Press Start 2P',
      devanagari: 'Poppins',
      bengali: 'Noto Sans Bengali Variable',
      telugu: 'Noto Sans Telugu Variable',
      tamil: 'Noto Sans Tamil Variable',
      thai: 'Noto Sans Thai Variable',
    },
  },];

/** The stack a template falls back to when it names none, or names one this build does not ship. */
export const DEFAULT_FONT_STACK_ID = 'inter';
